language: python
install: pip install -r requirements.txt
branches:
  only:
    - gh-pages # needs to be explicitely included
    - /.*/
script:
   - make check
   - python scripts/check.py --strict $(git diff --name-only --diff-filter=AM HEAD...$TRAVIS_BRANCH)
before_deploy:
    - make clean
    - make
deploy:
  provider: pages
  skip-cleanup: true
  github-token: $GITHUB_TOKEN  # Set in travis-ci.org dashboard, marked secure
  name: Robot Fairhurst
  keep-history: true
  on:
    # Only deploy from gh-pages branch itself
    branch: gh-pages
    # Don't deploy if the last commit is by Travis itself
    condition:  $(git log --format="%cn" -n 1) != "Robot Fairhurst (from Travis CI)"
