language: python

cache: pip

install: pip install -r requirements.txt

branches:
  only:
    - gh-pages # needs to be explicitely included
    - /.*/

script:
   - make check
   - export CHANGED_FILES=$(git diff --name-only $TRAVIS_COMMIT_RANGE)
   - echo $CHANGED_FILES
   - echo $TRAVIS_PULL_REQUEST
   # We only execute strict tests if we have changed files and are a pull request
   - if [ -z "$CHANGED_FILES" ]; then echo "No files available"; elif [ "${TRAVIS_PULL_REQUEST}" != "false" ]; then python scripts/check.py --strict $CHANGED_FILES; fi

before_deploy:
    - make clean
    - make

deploy:
  provider: pages
  skip-cleanup: true
  github-token: $GITHUB_TOKEN  # Set in travis-ci.org dashboard, marked secure
  name: Robot Fairhurst
  keep-history: true
  on:
    # Only deploy from gh-pages branch itself
    branch: gh-pages
    # Don't deploy if the last commit is by Travis itself
    condition:  $(git log --format="%cn" -n 1) != "Robot Fairhurst (from Travis CI)"
