name: josm_check

# Run this workflow every time a new commit pushed to your repository
on: [ push, pull_request ]

jobs:
    rstcheck:
        name: josm_check
        runs-on: ubuntu-latest

        steps:
            -   name: Checkout code
                uses: actions/checkout@v2

            -   name: Install xmllint
                run: sudo apt-get install libxml2-utils

            -   name: Set up Python
                uses: actions/setup-python@v2
                with:
                    python-version: 3.8

            -   name: Install Python dependencies
                run: python -m pip install shapely==1.7.1 lxml==4.6.0

            -   name: Create XML
                run: python scripts/convert_xml.py sources

            -   name: Download JOSM maps xsd
                run: wget https://raw.githubusercontent.com/openstreetmap/josm/master/resources/data/maps.xsd

            -   name: Run xmllint
                run: xmllint --schema maps.xsd imagery.xml --noout
