name: Check strict_check.py

on:
  pull_request:
    paths:
      - "scripts/libeli/*"
      - "scripts/*.py"
      - "requirements*.txt"

jobs:
  check:
    name: Check PR
    runs-on: [ubuntu-20.04]
    if: "!contains(github.event.head_commit.message, '[ci skip]') && !contains(github.event.head_commit.message, '[skip ci]')"
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v3
        with:
          python-version: "3.10"

      - name: Install Python dependencies
        run: |
          python -m pip install -U pip wheel
          python -m pip install -r requirements.txt

      # Rudimentary check if strict_check.py works by applying it to a small subset of sources.
      # This is expected to fail as sources might fail the strict check.
      # However, there should be no Python errors or obvious wrong checks present.
      - name: Strict check
        run: |
          python scripts/strict_check.py sources/europe/ch/*

      - name: Basic check
        run: find sources -name \*.geojson | xargs python scripts/check.py
